### ISSUE TITLE
sourcing within tests is broken

### ISSUE THREAD

**Issue by nwmcsween** [rylnd/shpec#121]
When creating tests a developer would generally want to do something like:
````
. ../../some_script.sh

describe "some_script"...
````

but since shpec 'sources' tests the relative path isn't valid anymore.

**Comment by rylnd** [comment]
@nwmcsween `$SHPEC_ROOT` is available as a reference point; you can see it being used in [our tests](https://github.com/rylnd/shpec/blob/master/shpec/shpec_shpec.sh#L178-L199).

You can also always source an absolute path, or pass the relative path plus PWD as a variable, e.g.

```bash
SCRIPT_PATH=$PWD/../../some_script.sh
```

and then use that in your test.

But in general, yes: because we don't know where the script is going to be run from, relative paths are not guaranteed to work.

**Comment by rylnd** [comment]
@nwmcsween I'm going to close this for now. Please feel free to stop by [the gittr room](https://gitter.im/rylnd/shpec) if you have support questions, or do open/reopen an issue if you feel there is a bug or missing feature.
